Added contributing file
Added bestpractices badge

Update readme

Update readme

Update readme

Update readme

Update Copyright

Added Deniz to the list of contributors

Added fair-software.yml

Update zenodo file

Minor

Minor

Update github workflows

Update github workflows

Update scripts for generating json files

Added more contributors

Update codemeta.json

Update codemeta.json

Update codemeta.json

Minor change readme

Minor change

Clang-format

Update authors

Minor change for zenodo

Update cleanup_cache.yml

Deleted old folders xball, mfi and lumon

Added a display for cmake status

Added a display for SUPPORTED_CXX_STANDARDS

Added a display for CMAKE_CXX_STANDARD

Removed old detector classes for lumon, mfi and xball

Removed xball from compilehelper/CMakeLists.txt

Added color to supported C++ standards

Minor change in the general CMakeLists-txt

diff --git a/.github/workflows/cleanup_cache.yml b/.github/workflows/cleanup_cache.yml
--- a/.github/workflows/cleanup_cache.yml
+++ b/.github/workflows/cleanup_cache.yml
@@ -14,23 +14,36 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Setup Git
-        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"
+      - name: Debug gh CLI
+        run: |
+          gh --version
+          gh auth status
+          gh extension list
+
+      - name: Update GitHub CLI
+        run: sudo apt-get install gh
+
+      - name: Install and Verify gh-actions-cache Extension
+        run: |
+          gh extension install actions/gh-actions-cache || exit 1
+          gh extension list | grep gh-actions-cache || (echo "Extension installation failed" && exit 1)
+
+      - name: Test actions-cache list
+        run: |
+          gh actions-cache list -R R3BRootGroup/R3BRoot -L 5 || echo "Failed to list caches"
 
       - name: Cleanup
         run: |
-          gh extension install actions/gh-actions-cache || exit 1
-          
           echo "Fetching list of cache keys"
           cacheKeys=$(gh actions-cache list -R R3BRootGroup/R3BRoot -L 100 | cut -f 1 | grep -v 'build-deps') || exit 1
 
-          ## Setting this to not fail the workflow while deleting cache keys. 
           set +e
           echo "Deleting old caches..."
           for cacheKey in $cacheKeys
           do
-              gh actions-cache delete $cacheKey -R R3BRootGroup/R3BRoot --confirm || exit 1
+              gh actions-cache delete $cacheKey -R R3BRootGroup/R3BRoot --confirm || echo "Failed to delete $cacheKey"
           done
           echo "Done"
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
